### ISSUE TITLE
Where to start?

### ISSUE THREAD

**Issue by r-preston** [r-preston/MPhysProject2021#1]
Some questions that come to mind:
- What is the example code doing?
- What form does the data have?
  * has the example code data already been processed?
- The W boson mass is affected by many sources of uncertainty, which area are we going to focus on reducing?

**Comment by mvesteri** [comment]
* The example code plots the transverse momentum distribution of a sample of isolated muons, which contains a lot of W -> mu nu events plus some background.
* The data are in a `TTree` format as described in [the root pages](https://root.cern.ch/doc/master/classTTree.html). This is a reduced final analysis data format. Almost all final analysis is done with data in this sort of format. A lot of processing (reconstruction, filtering, etc...) will have been done in between the detector and these files.
* On the W mass uncertainties I answer in a moment...

**Comment by mvesteri** [comment]
OK so @r-preston @lmcairns we will actually begin with a measurement that supports the W mass measurement, namely the measurement of the W and Z production cross sections. This is important for the W mass because the cross sections constrain the parton distribution functions (i.e. how likely is it to find an up quark with a particular momentum fraction when you probe the proton at a particular energy scale). The parton distribution functions are one of the biggest sources of modelling uncertainty for the W mass.

The particular data set that you are looking at has never been looked at before in this context. It is special because it is from a low energy run at $`\sqrt{s} = 5`$ TeV. Most of our data is a $`\sqrt{s} = 13`$ TeV. We much much more of the high energy data but the low energy data has unique sensitivity to the proton structure at larger momentum fractions.

I think this cross section analysis naturally splits into two parts, which could be split between @r-preston and @lmcairns.
* The measurement of the cross sections.
* The calculation of the "hypothesis", i.e. the theory predictions of the cross sections.

**Comment by mvesteri** [comment]
I have a suggested next step though: you should both try to search for the Z boson in the dataset to familiarise yourself with the helper functions for 4-momentum-vectors. More details in a moment.

**Comment by mvesteri** [comment]
* Suggest that @lmcairns @r-preston volunteer for python and C versions to play with. In the following I suggest what would change in the python code.
* Suggest to write new C and python code `findZpeak.{py,cpp}` for example.
* [here](https://github.com/r-preston/MPhysProject2021/blob/master/example.py#L11) in the python script you should look at the location `Z/DecayTree`.
* In that `TTree` there are the `branches`: `mup_PT,mup_ETA,mup_PHI` which are the transverse momentum, pseudorapidity and azimuthal angle of the positively charged muon. The equivalent branches for the negative muon are prefixed with `mum_`. The transverse momentum is in units of MeV.
* In the `TTree::Draw()` function you can put a `TFormula` like `ch.Draw('mup_PT+mup_ETA>>'+histogram.GetName())`.
* Can you work out a formula for the invariant mass of the two muon system and fill a histogram with it?
* The same should work in the C++ code.

Just let me know if you have any questions.
