### ISSUE TITLE
Measurement: Snapshot of Workflow and Next Steps

### ISSUE THREAD

**Issue by lmcairns-mphys** [r-preston/MPhysProject2021#23]
Hi @mvesteri 

Here is the report produced by my analysis, with a snapshot of the workflow written up as requested.
[measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/5632150/measurement_report.pdf)

What would be the next steps that I should focus on?

**Comment by mvesteri** [comment]
@lmcairns that's great. I'll send some feedback on that report. 

OK, so the next step is to look at the W data.

The data (i.e. not simulation "data") are in the same file `5TeV_2017_32_Down_EW.root` but under the paths `WpIso/DecayTree` and `WmIso/DecayTree` for W+ and W-, respectively.

First try plotting the muon pT distribution, and see if you can identify the W signal contribution.

Note that with no further selection the sample will have a lot of hadronic background.

The main variable that discriminates between the hadronic background and the W [->mu nu] signal is the "isolation". That is essentially the sum of particle transverse momenta within a cone around the muon.

Try plotting the 2D distribution of `1/mu_PT` versus `TMath::Log10(TMath::Max(0.1,1.e-3*mu_PTSUMCONE040))`. 
It is better to plot the log10 of the isolation because the background (and the signal) have a power-law distribution. If you take the log then this makes a nice "Gaussian-like" shape. The `TMath::Max` is to suppress the zero values before taking the log. In this 2D plane the signal should stand out.

Then we'll want to start trying to build a model of the sample using simulated signals and backgrounds...

I'd suggest to start by writing a new script for making plots with the W sample.

**Comment by lmcairns-mphys** [comment]
@mvesteri
Thank you, will look at the W data now.
I made a very small update to the report, realised I'd missed some details about the histogram plotting code. Here is the updated version: 
[measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/5637030/measurement_report.pdf)
